name: absen_qrcode
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.12
  shared_preferences: ^2.2.1
  cupertino_icons: ^1.0.6
  auto_route: ^7.8.4
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  firebase_auth: ^4.10.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^2.1.0
  flutter_barcode_scanner: ^2.0.0
  flutter_toastr: ^1.0.3
  firebase_core: ^2.7.1
  firebase_storage: ^11.0.15
  cloud_firestore: ^4.4.5
  firebase_database: ^10.1.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
  assets:
    - images/
